### ISSUE TITLE
開発を進める方

### ISSUE THREAD

**Issue by RINNUXEI** [enpitut/Tsukucha#3]
# 概要

分散PBLも始まったので、開発を進めましょう。
# TODO

短期合宿中に提案された機能に基づき、一応以下のTODOリストを整えた。
- [x] 今Repositoryに「HandsFreeRecipe」と「TsukuchaAPP」という2つのProjectもあるが、まず1つにして共同開発をしましょう
- [x] スリープ防止機能 @purple27 
- [x] タイマー機能 @Daiki-Nakamura 
- [x] UI @ZhangYunze 
- [x] 音声認識機能 @Kotaka-Zhang 
# 開発の進め方
1. Projectを1つにしてから各自masterからbranchを作る。branch名は機能がわかるようにする。(e.g. speech-recognition)
2. Local Repositoryにcommitする時は,commentに詳細は書かなくていい。
3. 進捗がみんなにわかるように、タスクが完成していなくてもPull Requestを出し、タイトルに[WIP]をつける
4. タスクが完成できたら[WIP]を外し、自分でmergeする。
5. 問題がある時Issuesを立て、必要あればメンターの方々も@でmentionして助けを求める。
# 参考リンク

基本みんなともにGitHub初心者なので、ここに自分が見つけたGitHubの勉強情報を貼っておく
- [Markdown (GitHub上でcommentやissuesなどを書く時の文法)](https://guides.github.com/features/mastering-markdown/)
- [Git用語集](http://toggtc.hatenablog.com/entry/2012/03/09/230931)

**Comment by ug23** [comment]
:+1: 
GitHubで`@` からメンターのGitHubIDを打つとmensionがこっちに届きます

参考リンク貼っておきます
http://www.slideshare.net/matsukaz/git-28304397
http://www.slideshare.net/kotas/git-15276118
http://k.swd.cc/learnGitBranching-ja/ （右下から言語を変えられます

中文な教科書
https://git-scm.com/book/zh-tw/v1
https://github.com/gotgit/gotgithub

**Comment by chiemi627** [comment]
:+1: 
わからなかったら聞いてね。
最初は10分〜30分ぐらいですぐ作れちゃう機能で試してみましょう。
というか最初だけじゃなくてずっとそのくらいのペースでこまめに
プルリクしていくのがいいですよ！

そして誰かがプルリクしたときのレビュー、すぐ返せるようにみんなで
ルール決めとくといいです。

とにかくどんどんやってみるのが吉です。

**Comment by RINNUXEI** [comment]
@chiemi627 コメントありがとうございます。

> そして誰かがプルリクしたときのレビュー、すぐ返せるようにみんなで ルール決めとくといいです。

これはPull Requestのフォーマットを決めとくってことですか？

**Comment by chiemi627** [comment]
いえいえ、フォーマットというより「誰が率先してレビューする（もちろん
ほかの人でも大歓迎）」とか「何人レビューしたらマージしていい」とか
「その日のうちにお返事する」とか「わからない場合もなんか反応する」
とかそういうルールです。

プルリクが誰にも見てもらえないと悲しくなりますので＾＾

**Comment by RINNUXEI** [comment]
:smiley: 分かりました。ありがとうございます！
